### ISSUE TITLE
concatena-hash

### ISSUE THREAD

**Issue by draggmen** [scsjcm/verifactu-PHP#1]
Hola, Hacienda ya ha publicado un pdf con ejemplos de cómo calcular el hash.
https://www.agenciatributaria.es/static_files/AEAT_Desarrolladores/EEDD/IVA/VERI-FACTU/Veri-Factu_especificaciones_huella_hash_registros.pdf
Mirando el fichero contena-hash.php la creación de la cadena es incorrecta, hay que poner los nombre de los campos.

Esta es mi función para crear la cadena y el resultado concuerda con los ejemplos de la documentación de Hacienda.

public function getHashVerifactu($idEmisoraFactura,$numFacturaSerie,$fechaExpedicion,$tipoFactura,$cuotaTotal,$importeTotal,$huellaAnterior,$fechaUsoHorarioRegistro){
    $cadena = "IDEmisorFactura=$idEmisoraFactura&NumSerieFactura=$numFacturaSerie&FechaExpedicionFactura=$fechaExpedicion&TipoFactura=$tipoFactura&CuotaTotal=$cuotaTotal&ImporteTotal=$importeTotal&Huella=$huellaAnterior&FechaHoraHusoGenRegistro=$fechaUsoHorarioRegistro";
    return hash('sha256', $cadena);
}

Por si puede actualizar el fichero.
Gracias,

**Comment by scsjcm** [comment]
> Hola, Hacienda ya ha publicado un pdf con ejemplos de cómo calcular el hash. https://www.agenciatributaria.es/static_files/AEAT_Desarrolladores/EEDD/IVA/VERI-FACTU/Veri-Factu_especificaciones_huella_hash_registros.pdf Mirando el fichero contena-hash.php la creación de la cadena es incorrecta, hay que poner los nombre de los campos.
> 
> Esta es mi función para crear la cadena y el resultado concuerda con los ejemplos de la documentación de Hacienda.
> 
> public function getHashVerifactu($idEmisoraFactura,$numFacturaSerie,$fechaExpedicion,$tipoFactura,$cuotaTotal,$importeTotal,$huellaAnterior,$fechaUsoHorarioRegistro){ $cadena = "IDEmisorFactura=$idEmisoraFactura&NumSerieFactura=$numFacturaSerie&FechaExpedicionFactura=$fechaExpedicion&TipoFactura=$tipoFactura&CuotaTotal=$cuotaTotal&ImporteTotal=$importeTotal&Huella=$huellaAnterior&FechaHoraHusoGenRegistro=$fechaUsoHorarioRegistro"; return hash('sha256', $cadena); }
> 
> Por si puede actualizar el fichero. Gracias,

muchas gracias por el aporte, lo cambio ahora mismo :)
